//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Experience()
        {
            this.IdExperienceGrade = new HashSet<ExperienceGrade>();
            this.Evaluation = new HashSet<Evaluation>();
            this.Objective = new HashSet<Objective>();
            this.HistoryExperience = new HashSet<HistoryExperience>();
            this.Document = new HashSet<Document>();
            this.ExperienceLineThematic = new HashSet<ExperienceLineThematic>();
            this.ExperiencePopulationGroup = new HashSet<ExperiencePopulationGroup>();
        }
    
        public int Id { get; set; }
        public string NameExperiences { get; set; }
        public string Summary { get; set; }
        public string Methodologies { get; set; }
        public string Transfer { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public string Code { get; set; }
        public System.DateTime DeleteAt { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int UserId { get; set; }
        public int InstitutionId { get; set; }
    
        public virtual verification Idverification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienceGrade> IdExperienceGrade { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objective> Objective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryExperience> HistoryExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienceLineThematic> ExperienceLineThematic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperiencePopulationGroup> ExperiencePopulationGroup { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
