//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Usuarios { get; set; }
        public virtual DbSet<Rol> RolSet { get; set; }
        public virtual DbSet<RolPermission> Rol_Permisos { get; set; }
        public virtual DbSet<UserRol> Usuario_Rols { get; set; }
        public virtual DbSet<Permission> Permisos { get; set; }
        public virtual DbSet<HistoryExperience> Historial_Experiencias { get; set; }
        public virtual DbSet<State> Estados { get; set; }
        public virtual DbSet<Evaluation> Evaluacions { get; set; }
        public virtual DbSet<EvaluationCriteria> Evaluacion_Criterios { get; set; }
        public virtual DbSet<Criteria> Criterios { get; set; }
        public virtual DbSet<Experience> Experiencias { get; set; }
        public virtual DbSet<Objective> Objectivos { get; set; }
        public virtual DbSet<ExperiencePopulationGroup> Experiencia_Grupo_Poblacionals { get; set; }
        public virtual DbSet<PopulationGrade> GrupoPoblacionals { get; set; }
        public virtual DbSet<verification> Verificacions { get; set; }
        public virtual DbSet<ExperienceGrade> ExperienciaGrados { get; set; }
        public virtual DbSet<Grade> Grados { get; set; }
        public virtual DbSet<Institution> Institucions { get; set; }
        public virtual DbSet<Document> Documentos { get; set; }
        public virtual DbSet<ExperienceLineThematic> ExperienciaLineaTematicas { get; set; }
        public virtual DbSet<LineThematic> LineaTematicas { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
    }
}
