//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPermission
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public int PermissionId { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
